### PR TITLE
Bug/list remove undo broke

### LINKED ISSUE #87: Undo remove from list broken
The two other undos seem to work, but for this I get some error message about "'List<int>' is not a subtype of type 'List<Album>'"

### PR DESCRIPTION
**Pull request by TNorbury**
Started off fixing an issue related to undo, ended up uncovering more than a few bugs. All resolved now and (as far as I can tell) are now covered by tests :)

fixes #87

### CODE REVIEW

File: lib/data/database/album_database/album_database_hive.dart [hunk 1]
```diff
@@ -58,23 +58,23 @@ class AlbumDatabaseHive with ChangeNotifier implements AlbumDatabase {
   @override
   void addAlbumToList(AlbumList list, Album album) {
     list.addAlbumToList(album.getId());
```
Comment (TNorbury) [inline lib/data/database/album_database/album_database_hive.dart:60]: Make sure both the list and album have ids

File: lib/data/database/album_database/album_database_hive.dart [hunk 2]
```diff
@@ -58,23 +58,23 @@ class AlbumDatabaseHive with ChangeNotifier implements AlbumDatabase {
...
+    _albumListBox.put(list.key, list);
   }
 
   @override
   void addAlbumsToList(AlbumList list, List<Album> albumsToAdd) {
     for (Album album in albumsToAdd) {
       list.addAlbumToList(album.getId());
     }
-    list.save();
+    _albumListBox.put(list.key, list);
```
Comment (TNorbury) [inline lib/data/database/album_database/album_database_hive.dart:69]: nice, lol
Make sure both the list and album have ids

File: lib/data/database/album_database/album_database_hive.dart [hunk 3]
```diff
@@ -58,23 +58,23 @@ class AlbumDatabaseHive with ChangeNotifier implements AlbumDatabase {
...
   }
 
   @override
   void addAlbumsToListFromIds(AlbumList list, List<int> albumsToAdd) {
     for (int album in albumsToAdd) {
       list.addAlbumToList(album);
     }
-    list.save();
+    _albumListBox.put(list.key, list);
```
Comment (TNorbury) [inline lib/data/database/album_database/album_database_hive.dart:77]: Make sure both the list and album have ids

File: lib/data/database/album_database/album_database_hive.dart [hunk 4]
```diff
@@ -189,7 +189,7 @@ class AlbumDatabaseHive with ChangeNotifier implements AlbumDatabase {
   @override
   Future<void> removeAlbumFromList(AlbumList list, Album album) async {
     list.removeAlbumFromList(album);
-    list.save();
+    _albumListBox.put(list.key, list);
```
Comment (TNorbury) [inline lib/data/database/album_database/album_database_hive.dart:192]: Make sure both the list and album have ids

File: lib/routes/album_list_info/widgets/delete_album_list_button.dart [hunk 5]
```diff
@@ -25,11 +23,17 @@ class DeleteAlbumListButton extends StatelessWidget {
...
       child: Text("Delete List"),
       onPressed: () async {
-        this._albumListPresenter.removeAlbumList(this._albumList);
+        AlbumListPresenterInterface db =
+            Provider.of<AlbumListPresenterInterface>(
+          context,
+          listen: false,
+        );
 
         // List doesn't exist, so we'll leave when the delete is confirmed.
```
Comment (TNorbury) [inline lib/routes/album_list_info/widgets/delete_album_list_button.dart:32]: reword

File: lib/routes/album_list_info/widgets/delete_album_list_button.dart [hunk 6]
```diff
@@ -25,11 +23,17 @@ class DeleteAlbumListButton extends StatelessWidget {
     return RaisedButton(
       child: Text("Delete List"),
       onPressed: () async {
-        this._albumListPresenter.removeAlbumList(this._albumList);
+        AlbumListPresenterInterface db =
```
Comment (TNorbury) [inline lib/routes/album_list_info/widgets/delete_album_list_button.dart:26]: Use the presenter

File: test/route_tests/album_list_info_test.dart [hunk 7]
```diff
@@ -0,0 +1,268 @@
...
+      await tester.tap(find.byType(DeleteAlbumListButton));
+      await tester.pumpAndSettle();
+
+      // After deletion, we should be back at the album lists view
+      expect(find.byType(AlbumListsView), findsOneWidget);
+
+      // There shouldn't be anything in the database
+      expect(db.getAlbumLists().length, 0);
+
+      // Verify the undo button work
```
Comment (TNorbury) [inline test/route_tests/album_list_info_test.dart:150]: "works"

File: lib/routes/album_list_info/widgets/delete_album_list_button.dart (hunk 6 above)
Comment (TNorbury) [reply lib/routes/album_list_info/widgets/delete_album_list_button.dart:26]: lol, I was u dummy xD!!
